### PR TITLE
PCA fixes

### PR DESCRIPTION
**Pull request by pumpikano**
This PR improves the Spark PCA code with some minor improvements. It also adds a simple script to demonstrate how to permute a PCA matrix to balance variance before the first stage of LOPQ quantization.

@huyng

### CODE REVIEW

**Comment by huyng** [comment]
Nice, curious what's the diff between the eigh vs eig function? Does this mean the results we had previously generated with the pca features were incorrectly computed?

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by pumpikano** [comment]
Per [docs](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.linalg.eig.html), `linalg.eig` works on general square matrices while `linalg.eigh` is for symmetric (our case) or Hermitian matrices. In my tests, I found `linalg.eigh` to be significantly faster for large symmetric matrices. That change is an optimization and does not change correctness.

**Comment by huyng** [comment]
:+1:

**Pull request merged**
